Feature/optimization for agilex
intel/hexl-fpga pull request #22
Opened 2022-09-21 14:13 UTC by wangyon1

2022-09-21 16:00 UTC, ymeng-git requested changes
comment out the call to the utility function copy_buffer_to_device().  The rest looks good.

2022-09-21 16:00 UTC, ymeng-git commented on host/src/fpga.cpp
> +    KeySwitch_events_write_[obj_id][0].wait();
For release, we can comment out line 1280-1281, and add a comment to explain that copy_buffer_to_device() and wait() is a utility to force blocked write, and to facilitate performance measure on FPGA.  The release is to support streaming, and blocking write will slow things down.

2022-09-21 20:21 UTC, ymeng-git commented
Could you enable github signing of your commits with your GPG key?  The unsigned/unverified commits will not go through the merge request.

2022-09-27 02:50 UTC, wangyon1 commented on host/src/fpga.cpp
> +    KeySwitch_events_write_[obj_id][0].wait();
Done.

2022-09-27 06:41 UTC, ymeng-git approved these changes

2022-09-27 08:56 UTC, yzhou79 approved these changes

2022-09-27 16:33 UTC, merged